version: "3"
services:
  mongo:
    extends:
      file: docker-compose.yml
      service: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: roombot
      ME_CONFIG_MONGODB_ADMINPASSWORD: roombot
      ME_CONFIG_MONGODB_URL: mongodb://roombot:roombot@mongo:27017/
