version: "3"
services:
  redis:
    build: ./redis
    ports:
      - 6379:6379
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: roombot
      MONGO_INITDB_ROOT_PASSWORD: roombot

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: roombot
      ME_CONFIG_MONGODB_ADMINPASSWORD: roombot
      ME_CONFIG_MONGODB_URL: mongodb://roombot:roombot@mongo:27017/
