version: "3"
services:
  app:
    build: ./
    depends_on:
      - redis
      - mongo
    restart: always
    env_file:
      - ./env/bot.env
      - ./env/mongo.env
    environment:
      MONGO_URL: "mongo:27017"

  redis:
    build: ./redis
    ports:
      - 6379:6379
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./env/mongo.env
