version: "3"
services:
  app:
    build: ./
    depends_on:
      - redis
      - mongo
    restart: always
    env_file:
      - bot.env
      - mongo.env

  redis:
    build: ./redis
    ports:
      - 6379:6379
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - mongo.env
