version: "3"
services:
  app:
    build: ./
    depends_on:
      - redis
      - mongo
    restart: always
    env_file:
      - ./env/bot.env
      - ./env/redis.env

  redis:
    build: ./redis
    ports:
      - 6379:6379
    restart: always
    env_file:
      - ./env/redis.env
      

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./env/mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - ./env/mongo-express.env
    profiles:
      - debug
